/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:Window:634332:
  appc.background(230);
} //_CODE_:Window:634332:

public void colourChangeClicked(GButton source, GEvent event) { //_CODE_:colourChange:897214:
  if(!textbox.show){
   changeFixtureColour("Random");
  }
} //_CODE_:colourChange:897214:

public void addProductsClicked(GButton source, GEvent event) { //_CODE_:addProducts:854692:
   addProducts();
} //_CODE_:addProducts:854692:

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:loadStore:472118:
} //_CODE_:loadStore:472118:

public void loadStoreButtonClicked(GButton source, GEvent event) { //_CODE_:loadStoreButton:532855:
  load(loadStore.getSelectedText());
} //_CODE_:loadStoreButton:532855:

public void FixturePresetsDropdownChanged(GDropList source, GEvent event) { //_CODE_:fixturePresetsDropdown:951029:
} //_CODE_:fixturePresetsDropdown:951029:

public void addFixtureButtonClicked(GButton source, GEvent event) { //_CODE_:addFixtureButton:862695:
  String selectedPreset = fixturePresetsDropdown.getSelectedText();
  presetIndex = int(selectedPreset.substring(0, selectedPreset.indexOf(")"))) - 1;
  addFixture();
} //_CODE_:addFixtureButton:862695:

public void renameFixtureClicked(GButton source, GEvent event) { //_CODE_:renameFixture:858910:
  renameFixture();
} //_CODE_:renameFixture:858910:

public void replaceProductsClicked(GButton source, GEvent event) { //_CODE_:replaceProducts:821293:
  reenterProducts();
} //_CODE_:replaceProducts:821293:

public void recalculatePathButtonClicked(GButton source, GEvent event) { //_CODE_:recaluclatePathButton:975154:
  int numFixtures = fixtures.size();
      allDistances = new float[numFixtures][numFixtures];
      optimalPaths = new String[numFixtures][numFixtures];
      
      recalculatePath(); //Manually recalculating the optimal path
} //_CODE_:recaluclatePathButton:975154:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  Window = GWindow.getWindow(this, "Window title", 0, 0, 300, 400, JAVA2D);
  Window.noLoop();
  Window.setActionOnClose(G4P.KEEP_OPEN);
  Window.addDrawHandler(this, "win_draw1");
  colourChange = new GButton(Window, 37, 204, 100, 40);
  colourChange.setTextAlign(GAlign.MIDDLE, GAlign.MIDDLE);
  colourChange.setText("Change Fixture Colour");
  colourChange.addEventHandler(this, "colourChangeClicked");
  addProducts = new GButton(Window, 158, 205, 100, 40);
  addProducts.setText("Add Products To Fixture");
  addProducts.addEventHandler(this, "addProductsClicked");
  loadStore = new GDropList(Window, 49, 61, 90, 80, 3, 10);
  loadStore.setItems(loadStrings("list_472118"), 0);
  loadStore.addEventHandler(this, "dropList1_click1");
  loadStoreButton = new GButton(Window, 55, 12, 80, 30);
  loadStoreButton.setText("Load Store");
  loadStoreButton.addEventHandler(this, "loadStoreButtonClicked");
  fixturePresetsDropdown = new GDropList(Window, 149, 58, 90, 120, 5, 10);
  fixturePresetsDropdown.setItems(loadStrings("list_951029"), 0);
  fixturePresetsDropdown.addEventHandler(this, "FixturePresetsDropdownChanged");
  addFixtureButton = new GButton(Window, 160, 10, 80, 30);
  addFixtureButton.setText("Add Fixture");
  addFixtureButton.addEventHandler(this, "addFixtureButtonClicked");
  renameFixture = new GButton(Window, 50, 253, 80, 30);
  renameFixture.setText("Rename Fixture");
  renameFixture.addEventHandler(this, "renameFixtureClicked");
  replaceProducts = new GButton(Window, 152, 264, 80, 30);
  replaceProducts.setText("Replace Products");
  replaceProducts.addEventHandler(this, "replaceProductsClicked");
  recaluclatePathButton = new GButton(Window, 39, 154, 100, 40);
  recaluclatePathButton.setText("Recalculate Optimal Path");
  recaluclatePathButton.addEventHandler(this, "recalculatePathButtonClicked");
  Window.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow Window;
GButton colourChange; 
GButton addProducts; 
GDropList loadStore; 
GButton loadStoreButton; 
GDropList fixturePresetsDropdown; 
GButton addFixtureButton; 
GButton renameFixture; 
GButton replaceProducts; 
GButton recaluclatePathButton; 
